;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="State.Psycho",NewTagName="State.Psychosis")
+GameplayTagList=(Tag="Consumable.Battery",DevComment="")
+GameplayTagList=(Tag="Consumable.Food",DevComment="")
+GameplayTagList=(Tag="Consumable.Health",DevComment="")
+GameplayTagList=(Tag="Cooldown.Attack.Weapon",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash.In",DevComment="")
+GameplayTagList=(Tag="Cooldown.Dash.Out",DevComment="")
+GameplayTagList=(Tag="Damage.Calculation",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AmmoInMag",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AmmoInReserve",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AttackRange",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.AttackRate",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.Damage",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.Magasine",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.MaxAmmoInReserve",DevComment="")
+GameplayTagList=(Tag="Data.Weapon.ReloadValue",DevComment="")
+GameplayTagList=(Tag="Event.Ability.OutOfRange",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Dash",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Psychose",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Psychose.End",DevComment="")
+GameplayTagList=(Tag="Event.Attack.Psychose.Start",DevComment="")
+GameplayTagList=(Tag="Event.Damage",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.End",DevComment="")
+GameplayTagList=(Tag="Event.HitScan.Start",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Attack",DevComment="")
+GameplayTagList=(Tag="Event.Weapon.Equip",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Attack.Psychose",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Death",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.HitReaction",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Dash",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Movement.Straff",DevComment="")
+GameplayTagList=(Tag="GameplayAbility.Regen.Psychose",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Dash.Active",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Psychose",DevComment="")
+GameplayTagList=(Tag="Item.Equipment.Flashlight",DevComment="")
+GameplayTagList=(Tag="State.Dead",DevComment="")
+GameplayTagList=(Tag="State.ExecutingAbility",DevComment="")
+GameplayTagList=(Tag="State.Freeze.Active",DevComment="")
+GameplayTagList=(Tag="State.Freeze.Frozen",DevComment="")
+GameplayTagList=(Tag="State.Health.Low",DevComment="")
+GameplayTagList=(Tag="State.Movement",DevComment="")
+GameplayTagList=(Tag="State.Movement.Active",DevComment="")
+GameplayTagList=(Tag="State.Psychosis",DevComment="")
+GameplayTagList=(Tag="State.Psychosis.Active",DevComment="")
+GameplayTagList=(Tag="State.Psychosis.Regeneration",DevComment="")
+GameplayTagList=(Tag="Weapon.Fire",DevComment="")
+GameplayTagList=(Tag="Weapon.Melee.Wrench",DevComment="")
+GameplayTagList=(Tag="Weapon.Range.Rifle",DevComment="")

